name: Update Child Repositories

on:
  push:
    branches:
      - main

jobs:
  update_repos:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        run: |
          git config --global user.email "test.sky0010.com"
          git config --global user.name "SkySingh0010"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Submodule
        run: |
           git config --global credential.helper store
           git config --global user.email "you@example.com"
           git config --global user.name "Your Name"
           git submodule update --remote
           cd submodule_directory
           git config http.extraheader "AUTHORIZATION: token ${{ secrets.new_sec }}"
           git pull
