name: Update Child Repositories

on:
  push:
    branches:
      - main

jobs:
  update_repos:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git
        run: |
          git config --global user.email "test.sky0010.com"
          git config --global user.name "SkySingh0010"

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Submodule
        run: |
          git submodule update --remote
          git add .
          git diff-index --quiet HEAD || git commit -m "Update submodule with changes from template repository"
          git push
