name: Update Child Repositories

on:
  push:
    branches:
      - main  # Trigger the workflow on pushes to the main branch of the template repository

jobs:
  update_repos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update Submodule
        run: |
          git submodule update --remote
          git add .
          git commit -m "Update submodule with changes from template repository"
          git push
